use whiskers to generate themes
Daeraxa/catppuccin-halloy pull request #2
Opened 2024-06-30 09:04 UTC by tranzystorekk

2024-06-30 09:12 UTC, tranzystorekk commented
https://github.com/catppuccin/halloy/pull/1#issuecomment-2110824114 @uncenter I took a stab at contributing a whiskers change, hope it's okay

2024-06-30 13:08 UTC, uncenter requested changes

2024-06-30 13:08 UTC, uncenter commented on README.md
>      - Windows: `{FOLDERID_RoamingAppData}\halloy\themes`
```suggestion
1. Download your flavor of choice from [`themes/`](./themes/) to the `themes/` directory inside [Halloy's configuration directory](https://halloy.squidowl.org/configuration/index.html).
```

2024-06-30 13:08 UTC, uncenter commented on README.md
> +    - `theme = "catppuccin-frappe"`
```suggestion
2. Update the `theme` field of your `config.toml` to `catppuccin-<flavor>`, where `<flavor>` is your chosen flavor. For example, `theme = "catppuccin-frappe"`.
```

2024-06-30 13:08 UTC, uncenter commented on README.md
> +3. Restart Halloy
```suggestion
3. Restart Halloy to see the theme applied.
```

2024-06-30 13:08 UTC, uncenter commented on halloy.tera
> +name = "catppuccin-{{flavor.identifier}}"
```suggestion
  filename: "themes/catppuccin-{{ flavor.identifier }}.toml"
---
name = "catppuccin-{{ flavor.identifier }}"
```

More readable with better whitespace :)

2024-06-30 13:08 UTC, uncenter commented on halloy.tera
> +success = "#{{flavor.colors.green.hex}}"
```suggestion
background = "#{{ base.hex }}"
text = "#{{ text.hex }}"
action = "#{{ rosewater.hex }}"
accent = "#{{ subtext1.hex }}"
alert = "#{{ yellow.hex }}"
error = "#{{ red.hex }}"
info = "#{{ blue.hex }}"
success = "#{{ green.hex }}"
```

2024-06-30 13:39 UTC, uncenter approved these changes

2024-08-12 23:33 UTC, sgoudham approved these changes
@Daeraxa Are you happy if I go ahead and merge this? It would supercede the changes made in #1.

I know you're said pretty busy so no pressure to reply as soon as you see this notification. This PR looks good to me so I'll most likely merge in the coming days if you don't get to it before me :+1:

2024-09-03 09:14 UTC, tranzystorekk commented
Halloy has new pending theme config changes, and quite substantial ones: https://unstable.halloy.squidowl.org/configuration/themes/

It'll probably take me a bit to find correct palette maappings, so we should hold off merging for now.

2024-09-08 17:23 UTC, sgoudham commented
It might be worth merging as is now so that it's easier to generate the new mappings later on with the new configuration. Would be good to raise an issue for that. @tranzystorekk

2024-09-14 21:48 UTC, sgoudham commented
Making an "executive" decision to merge this and create a tracking issue on the repository for the configuration to be updated with the new mappings which someone can pick up.

Thanks for your work! @tranzystorekk

2024-09-14 21:49 UTC, merged